In [1]:
import pandas as pd
import numpy as np

# read in schools table
df = pd.read_csv('../scraping_school_data/schools.csv',encoding='latin1')
total_rows = int(df.size/4)
print(total_rows)
df

129

,School,Type,Street Address,Zip Code
0,Ballard,high school,1418 NW 65th St,98117
1,Center School,high school,305 Harrison St,98109
2,Cleveland,high school,5511 15th Ave S,98108
3,Franklin,high school,3013 S Mt Baker Blvd,98144
4,Garfield,high school,400 23rd Ave,98122
5,"Hale, Nathan",high school,10750 30th Ave NE,98125
6,Ingraham,high school,1819 N 135th St,98133
7,Interagency,high school,3528 S. Ferdinand St.,98118
8,Lincoln,high school,4400 Interlake Ave. N,98103
9,Middle College,high school,401 NE Northgate Way Ste. # 202,98125
10,Nova,high school,2410 E Cherry St.,98122
11,Rainier Beach,high school,8815 Seward Park Ave. S,98118
12,Roosevelt,high school,1410 NE 66th St,98115
13,Sealth,high school,2600 SW Thistle St,98126
14,Seattle World School,high school,1700 E. Union St.æ,98122
15,Skills Center,high school,unknown street,unknown zip
16,South Lake,high school,8601 Rainier Ave S,98118
17,West Seattle,high school,3000 California Ave SW,98116
18,"Addams, Jane",middle school,11051 34th Ave NE,98125
19,Denny,middle school,2601 SW Kenyon St,98126
20,"Eagle Staff, Robert",middle school,1330 N. 90th Street,98103
21,Eckstein,middle school,3003 NE 75th St,98115
22,Hamilton,middle school,1610 N 41st St,98103
23,"Kurose, Aki",middle school,3928 S Graham St,98118
24,Madison,middle school,3429 45th Ave SW,98116
25,McClure,middle school,1915 1st Ave W,98119
26,Meany,middle school,301 21st Ave E,98112
27,Mercer,middle school,1600 S Columbian,98108
28,Seattle World School,middle school,1700 E. Union St.æ,98122
29,Washington,middle school,2101 S Jackson St,98144
...,...,...,...,...
99,View Ridge,elementary school,7047 50th Ave NE,98115
100,Viewlands,elementary school,10525 3rd Ave NW,98177
101,Wedgwood,elementary school,2720 NE 85th St.,98115
102,West Seattle,elementary school,6760 34th Ave SW,98126
103,West Woodland,elementary school,5601 4th Ave NW,98107
104,Whittier,elementary school,1320 NW 75th St,98117
105,"Boren, Louisa",option,5950 Delridge Way SW,98106
106,Cedar Park,option,13224 37th Ave NE,98125
107,Center School,option,305 Harrison St,98109
108,Cleveland,option,5511 15th Ave S,98108
109,Licton Springs,option,1330 N. 90th St.,98103
110,McDonald,option,144 NE 54th St,98105
111,Orca,option,unknown street,unknown zip
112,Pathfinder,option,1901 SW Genesee Stæ,98106
113,Queen Anne,option,520 NE Ravenna Blvd,98155
114,Salmon Bay,option,1810 NW 65th Stæ,98117
115,South Shore,option,4800 S Henderson St,98118
116,"Stanford, John",option,4057 5th Ave NEæ,98105
117,Thornton Creek,option,7712 40th Avenue NE,98115
118,TOPS,option,2500 Franklin Ave Eæ,98102
119,"Wolf, Hazel",option,11530 12th Ave NEæ,98125
120,BRIDGES,alternative and service,unknown street,unknown zip
121,Cascade Parent Partnership,alternative and service,2919 1st Ave W.,98119
122,Interagency,alternative and service,3528 S. Ferdinand St.,98118
123,Middle College,alternative and service,401 NE Northgate Way Ste. # 202,98125
124,Nova,alternative and service,2410 E Cherry St.,98122
125,Original Van Asselt,alternative and service,8311 Beacon Ave S,98118
126,Seattle World School,alternative and service,1700 E. Union St.æ,98122
127,Skills Center,alternative and service,unknown street,unknown zip
128,South Lake,alternative and service,8601 Rainier Ave S,98118

In [2]:
# add option/alt column to schools data table
# remove rows that repeat school names

import time

option_alt = []

option_index = df['Type'] == 'option'
option_schools_table = df[option_index]
option_school_names = list(option_schools_table['School'])

alt_index = df['Type'] == 'alternative and service'
alt_schools_table = df[alt_index]
alt_school_names = list(alt_schools_table['School'])

all_school_df = df[0:105]
all_school_names = list(all_school_df['School'])
all_school_df

option_alt_schools = df[105:129]

for index, row in all_school_df.iterrows():
    if row['School'] in option_school_names:
        option_alt.append('option')
    elif row['School'] in alt_school_names:
        option_alt.append('alternative and service')
    else:
        option_alt.append('N/A')
        
all_school_df['option_alt'] = option_alt

total_rows = int(df.size/5)
i = 1
for index, row in option_alt_schools.iterrows():
    if row['School'] not in all_school_names:
        new_data = [row['School'],row['Type'],row['Street Address'],row['Zip Code'],row['Type']]
        all_school_df.loc[total_rows+i] = new_data
        i += 1
        #new_def = pd.DataFrame([row['School'],row['Type'],row['Street Address'],row['Zip Code'],row['Type']],
        #     columns=['School','Type','Street Address', 'Zip Code','option_alt'])
        #print(new_df)

#all_school_df = all_school_df.append()


all_school_df

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,School,Type,Street Address,Zip Code,option_alt
0,Ballard,high school,1418 NW 65th St,98117,N/A
1,Center School,high school,305 Harrison St,98109,option
2,Cleveland,high school,5511 15th Ave S,98108,option
3,Franklin,high school,3013 S Mt Baker Blvd,98144,N/A
4,Garfield,high school,400 23rd Ave,98122,N/A
5,"Hale, Nathan",high school,10750 30th Ave NE,98125,N/A
6,Ingraham,high school,1819 N 135th St,98133,N/A
7,Interagency,high school,3528 S. Ferdinand St.,98118,alternative and service
8,Lincoln,high school,4400 Interlake Ave. N,98103,N/A
9,Middle College,high school,401 NE Northgate Way Ste. # 202,98125,alternative and service
10,Nova,high school,2410 E Cherry St.,98122,N/A
11,Rainier Beach,high school,8815 Seward Park Ave. S,98118,N/A
12,Roosevelt,high school,1410 NE 66th St,98115,N/A
13,Sealth,high school,2600 SW Thistle St,98126,N/A
14,Seattle World School,high school,1700 E. Union St.æ,98122,alternative and service
15,Skills Center,high school,unknown street,unknown zip,alternative and service
16,South Lake,high school,8601 Rainier Ave S,98118,N/A
17,West Seattle,high school,3000 California Ave SW,98116,N/A
18,"Addams, Jane",middle school,11051 34th Ave NE,98125,N/A
19,Denny,middle school,2601 SW Kenyon St,98126,N/A
20,"Eagle Staff, Robert",middle school,1330 N. 90th Street,98103,N/A
21,Eckstein,middle school,3003 NE 75th St,98115,N/A
22,Hamilton,middle school,1610 N 41st St,98103,N/A
23,"Kurose, Aki",middle school,3928 S Graham St,98118,N/A
24,Madison,middle school,3429 45th Ave SW,98116,N/A
25,McClure,middle school,1915 1st Ave W,98119,N/A
26,Meany,middle school,301 21st Ave E,98112,N/A
27,Mercer,middle school,1600 S Columbian,98108,N/A
28,Seattle World School,middle school,1700 E. Union St.æ,98122,alternative and service
29,Washington,middle school,2101 S Jackson St,98144,N/A
...,...,...,...,...,...
80,McDonald,elementary school,144 NE 54th St,98105,option
81,McGilvra,elementary school,1617 38th Ave E,98112,N/A
82,Montlake,elementary school,2409 22nd Ave E,98112,N/A
83,"Muir, John",elementary school,3301 S Horton St,98144,N/A
84,North Beach,elementary school,9018 24th Ave NW,98117,N/A
85,Northgate,elementary school,11725 1st Ave NE,98125,N/A
86,Olympic Hills,elementary school,13018 20th Ave NE,98125,N/A
87,Olympic View,elementary school,504 NE 95th St,98115,N/A
88,Queen Anne,elementary school,520 NE Ravenna Blvd,98155,option
89,Rainier View,elementary school,11650 Beacon Ave S,98178,N/A
90,"Rogers, John",elementary school,4030 NE 109th St,98125,N/A
91,Roxhill,elementary school,7740 34th Ave SW,98126,N/A
92,Sacajawea,elementary school,9501 20th Ave NE,98115,N/A
93,Sand Point,elementary school,6208 60th Ave NE,98115,N/A
94,Sanislo,elementary school,1812 SW Myrtle St,98106,N/A
95,"Stanford, John",elementary school,4057 5th Ave NEæ,98105,option
96,Stevens,elementary school,1242 18th Ave E,98112,N/A
97,Thornton Creek,elementary school,7712 40th Avenue NE,98115,option
98,Van Asselt,elementary school,8311 Beacon Ave S,98118,N/A
99,View Ridge,elementary school,7047 50th Ave NE,98115,N/A
100,Viewlands,elementary school,10525 3rd Ave NW,98177,N/A
101,Wedgwood,elementary school,2720 NE 85th St.,98115,N/A
102,West Seattle,elementary school,6760 34th Ave SW,98126,N/A
103,West Woodland,elementary school,5601 4th Ave NW,98107,N/A
104,Licton Springs,option,1330 N. 90th St.,98103,option
105,BRIDGES,alternative and service,unknown street,unknown zip,alternative and service
106,Cascade Parent Partnership,alternative and service,2919 1st Ave W.,98119,alternative and service
107,Nova,alternative and service,2410 E Cherry St.,98122,alternative and service
108,Original Van Asselt,alternative and service,8311 Beacon Ave S,98118,alternative and service
109,South Lake,alternative and service,8601 Rainier Ave S,98118,alternative and service

In [ ]:
# lat/long data reversed
# using arcgis geocoder -- doesn't require a key and plays nicely with arcgis maps
'''
from opencage.geocoder import OpenCageGeocode

key = '63a88c0af7c646888e45bf4386df46d1'
geocoder = OpenCageGeocode(key)

long = []
lat = []

for index, row in all_school_df.iterrows():
        query = row["Street Address"]+", "+ "Seattle, WA "+row["Zip Code"]
        results = geocoder.geocode(query)
        
        if len(results) > 0:
            the_lat = results[0]['geometry']['lat']
            the_long = results[0]['geometry']['lng']

            lat.append(the_lat)
            long.append(the_long)
        else:
            the_lat = 'unknown'
            the_long = 'unknown'
            lat.append('unknown')
            long.append('unknown')
        
        print(the_lat, the_long)
'''

In [3]:
#geocoding with arcgis
from arcgis.geocoding import geocode

print(type(geocode))

lat = []
long = []
geocodes = []

for index, row in all_school_df.iterrows():
    query = row["Street Address"]+", "+ "Seattle, WA "+row["Zip Code"]
    print(query)
    results = geocode(query)
        
    if len(results) > 0:
        the_lat = results[0]['location']['x']
        the_long = results[0]['location']['y']

        lat.append(the_lat)
        long.append(the_long)
        geocodes.append(results[0])
    else:
        the_lat = 0
        the_long = 0
        lat.append(the_lat)
        long.append(the_long)
        geocodes.append({})
        
    print(index)
        #print(the_lat, the_long)

<class 'function'>
1418 NW 65th St , Seattle, WA 98117

AttributeError: 'NoneType' object has no attribute '_tools'

In [ ]:
all_school_df['latitude'] = lat
all_school_df['longitude'] = long
all_school_df['geocode'] = geocodes
all_school_df

In [ ]:
#all_school_df.to_csv('school_list.csv')
#all_school_df.to_pickle('school_list.pk1')

In [ ]:
import math
import matplotlib.pyplot as plt

lat_list = []
long_list = []
x_list = []
y_list = []
name_list = []

names = list(all_school_df['School'])

for i in range(len(lat)):
    if lat[i] != 0:
        lat_list.append(lat[i])
        long_list.append(long[i])
        name_list.append(names[i])

#fig, ax = plt.subplots()
ax = plt.axes([0, 0, 1, 3])

for i,txt in enumerate(name_list):
    ax.annotate(txt, (lat_list[i], long_list[i]))

plt.scatter(lat_list,long_list, norm = True)
plt.show()

In [ ]:
import random
from arcgis.gis import GIS
#from arcgis.geocoding import geocoding
my_gis = GIS()
seattle = my_gis.map("Seattle, WA")

i = 0
for school in geocodes:
    seattle.draw(school['location'], {"title" : n[i], "content" : school['address']},{
"type": "esriSMS",
 "style": "esriSMSSquare",
 "color": [random.randint(0,255),random.randint(0,255),random.randint(0,255),255],
 "size": random.randint(4,8),
 "angle": 0,
 "xoffset": 0,
 "yoffset": 0,
 "outline": 
  {
  "color": [random.randint(0,255),random.randint(0,255),random.randint(0,255),255],
   "width": 1
  }
})
    i+=1
    
seattle