In [15]:
import datetime
import pandas as pd
import numpy as np
from datascience import *
import random
from arcgis.gis import GIS

# read in schools table
school_df = pd.read_pickle('../geocoding_schools/cleaned_school_list.pk1')


#from arcgis.geocoding import geocoding
my_gis = GIS()
seattle = my_gis.map("Seattle, WA")

geocodes = school_df['geocode']
name = school_df['School']

i = 0
for school in geocodes:
    try:
        seattle.draw(school['location'], {"title" : name[i], "content" : school['address']},
                     {"type": "esriSMS","style": "esriSMSCircle","color": [0,255,0,255],"size": 6,
                      "angle": 0,"xoffset": 0,"yoffset": 0,
                      "outline": {"color": [0,0,0,255],"width": 0}})
    except:
        print("No address for:", (name[i]))
    i+=1
    
late_bus_df = pd.read_pickle('../scraping_bus_data/bus_data.pk1')
late_bus_select_df  = late_bus_df.loc[late_bus_df['Day'] == ]

,School,Type,Street Address,Zip Code,option_alt,latitude,longitude,geocode
0,Ballard,high school,1418 NW 65th St,98117,N/A,-122.375443,47.676036,"{'address': '1418 NW 65th St, Seattle, Washing..."
1,Center School,high school,305 Harrison St,98109,option,-122.351281,47.622121,"{'address': '305 Harrison St, Seattle, Washing..."
2,Cleveland,high school,5511 15th Ave S,98108,option,-122.313525,47.552310,"{'address': '5511 15th Ave S, Seattle, Washing..."
3,Franklin,high school,3013 S Mt Baker Blvd,98144,N/A,-122.293404,47.576477,"{'address': '3013 S Mt Baker Blvd, Seattle, Wa..."
4,Garfield,high school,400 23rd Ave,98122,N/A,-122.302634,47.605201,"{'address': '400 23rd Ave, Seattle, Washington..."
5,Nathan Hale,high school,10750 30th Ave NE,98125,N/A,-122.296121,47.708046,"{'address': '10750 30th Ave NE, Seattle, Washi..."
6,Ingraham,high school,1819 N 135th St,98133,N/A,-122.336233,47.726821,"{'address': '1819 N 135th St, Seattle, Washing..."
7,Interagency,high school,3528 S. Ferdinand St.,98118,alternative and service,-122.287113,47.557887,"{'address': '3528 S Ferdinand St, Seattle, Was..."
8,Lincoln,high school,4400 Interlake Ave. N,98103,N/A,-122.340631,47.660148,"{'address': '4400 Interlake Ave N, Seattle, Wa..."
9,Middle College,high school,401 NE Northgate Way Ste. # 202,98125,alternative and service,-122.323831,47.708510,"{'address': '401 NE Northgate Way, Seattle, Wa..."
10,Nova,high school,2410 E Cherry St.,98122,N/A,-122.301141,47.608023,"{'address': '2410 E Cherry St, Seattle, Washin..."
11,Rainier Beach,high school,8815 Seward Park Ave. S,98118,N/A,-122.264664,47.524105,"{'address': '8815 Seward Park Ave S, Seattle, ..."
12,Roosevelt,high school,1410 NE 66th St,98115,N/A,-122.312630,47.676563,"{'address': '1410 NE 66th St, Seattle, Washing..."
13,Sealth,high school,2600 SW Thistle St,98126,N/A,-122.366161,47.528299,"{'address': '2600 SW Thistle St, Seattle, Wash..."
14,Seattle World School,high school,1700 E. Union St.Ã¦,98122,alternative and service,-122.309280,47.612933,"{'address': '1700 E Union St, Seattle, Washing..."
15,Skills Center,high school,unknown street,unknown zip,alternative and service,0.000000,0.000000,{}
16,South Lake,high school,8601 Rainier Ave S,98118,N/A,-122.270014,47.525661,"{'address': '8601 Rainier Ave S, Seattle, Wash..."
17,West Seattle,high school,3000 California Ave SW,98116,N/A,-122.386701,47.576970,"{'address': '3000 California Ave SW, Seattle, ..."
18,Jane Addams,middle school,11051 34th Ave NE,98125,N/A,-122.292122,47.709836,"{'address': '11051 34th Ave NE, Seattle, Washi..."
19,Denny,middle school,2601 SW Kenyon St,98126,N/A,-122.366052,47.531851,"{'address': '2601 SW Kenyon St, Seattle, Washi..."
20,Robert Eagle Staff,middle school,1330 N. 90th Street,98103,N/A,-122.340502,47.694182,"{'address': '1330 N 90th St, Seattle, Washingt..."
21,Eckstein,middle school,3003 NE 75th St,98115,N/A,-122.294861,47.683018,"{'address': '3003 NE 75th St, Seattle, Washing..."
22,Hamilton,middle school,1610 N 41st St,98103,N/A,-122.338021,47.656846,"{'address': '1610 N 41st St, Seattle, Washingt..."
23,Aki Kurose,middle school,3928 S Graham St,98118,N/A,-122.282002,47.546032,"{'address': '3928 S Graham St, Seattle, Washin..."
24,Madison,middle school,3429 45th Ave SW,98116,N/A,-122.389514,47.572982,"{'address': '3429 45th Ave SW, Seattle, Washin..."
25,McClure,middle school,1915 1st Ave W,98119,N/A,-122.358343,47.636820,"{'address': '1915 1st Ave W, Seattle, Washingt..."
26,Meany,middle school,301 21st Ave E,98112,N/A,-122.304763,47.621574,"{'address': '301 21st Ave E, Seattle, Washingt..."
27,Mercer,middle school,1600 S Columbian,98108,N/A,-122.312673,47.563210,"{'address': '1600 S Columbian Way, Seattle, Wa..."
28,Seattle World School,middle school,1700 E. Union St.Ã¦,98122,alternative and service,-122.309280,47.612933,"{'address': '1700 E Union St, Seattle, Washing..."
29,Washington,middle school,2101 S Jackson St,98144,N/A,-122.304164,47.599250,"{'address': '2101 S Jackson St, Seattle, Washi..."
...,...,...,...,...,...,...,...,...
80,McDonald,elementary school,144 NE 54th St,98105,option,-122.326591,47.667913,"{'address': '144 NE 54th St, Seattle, Washingt..."
81,McGilvra,elementary school,1617 38th Ave E,98112,N/A,-122.284091,47.634075,"{'address': '1617 38th Ave E, Seattle, Washing..."
82,Montlake,elementary school,2409 22nd Ave E,98112,N/A,-122.303823,47.640626,"{'address': '2409 22nd Ave E, Seattle, Washing..."
83,John Muir,elementary school,3301 S Horton St,98144,N/A,-122.290572,47.573737,"{'address': '3301 S Horton St, Seattle, Washin..."
84,North Beach,elementary school,9018 24th Ave NW,98117,N/A,-122.387532,47.694861,"{'address': '9018 24th Ave NW, Seattle, Washin..."
85,Northgate,elementary school,11725 1st Ave NE,98125,N/A,-122.328841,47.714841,"{'address': '11725 1st Ave NE, Seattle, Washin..."
86,Olympic Hills,elementary school,13018 20th Ave NE,98125,N/A,-122.307252,47.724066,"{'address': '13018 20th Ave NE, Seattle, Washi..."
87,Olympic View,elementary school,504 NE 95th St,98115,N/A,-122.321283,47.697707,"{'address': '504 NE 95th St, Seattle, Washingt..."
88,Queen Anne,elementary school,520 NE Ravenna Blvd,98155,option,-122.322877,47.677019,"{'address': '520 NE Ravenna Blvd, Seattle, Was..."
89,Rainier View,elementary school,11650 Beacon Ave S,98178,N/A,-122.264309,47.498740,"{'address': '11650 Beacon Ave S, Seattle, Wash..."
90,John Rogers,elementary school,4030 NE 109th St,98125,N/A,-122.283822,47.707407,"{'address': '4030 NE 109th St, Seattle, Washin..."
91,Roxhill,elementary school,7740 34th Ave SW,98126,N/A,-122.375243,47.532842,"{'address': '7740 34th Ave SW, Seattle, Washin..."
92,Sacajawea,elementary school,9501 20th Ave NE,98115,N/A,-122.306913,47.698442,"{'address': '9501 20th Ave NE, Seattle, Washin..."
93,Sand Point,elementary school,6208 60th Ave NE,98115,N/A,-122.263495,47.673754,"{'address': '6208 60th Ave NE, Seattle, Washin..."
94,Sanislo,elementary school,1812 SW Myrtle St,98106,N/A,-122.358702,47.539139,"{'address': '1812 SW Myrtle St, Seattle, Washi..."
95,John Stanford,elementary school,4057 5th Ave NEÃ¦,98105,option,-122.323494,47.657511,"{'address': '4057 5th Ave NE, Seattle, Washing..."
96,Stevens,elementary school,1242 18th Ave E,98112,N/A,-122.308543,47.631924,"{'address': '1242 18th Ave E, Seattle, Washing..."
97,Thornton Creek,elementary school,7712 40th Avenue NE,98115,option,-122.285253,47.685646,"{'address': '7712 40th Ave NE, Seattle, Washin..."
98,Van Asselt,elementary school,8311 Beacon Ave S,98118,N/A,-122.288083,47.529125,"{'address': '8311 Beacon Ave S, Seattle, Washi..."
99,View Ridge,elementary school,7047 50th Ave NE,98115,N/A,-122.274362,47.680669,"{'address': '7047 50th Ave NE, Seattle, Washin..."
100,Viewlands,elementary school,10525 3rd Ave NW,98177,N/A,-122.360841,47.705967,"{'address': '10525 3rd Ave NW, Seattle, Washin..."
101,Wedgwood,elementary school,2720 NE 85th St.,98115,N/A,-122.297792,47.690251,"{'address': '2720 NE 85th St, Seattle, Washing..."
102,West Seattle,elementary school,6760 34th Ave SW,98126,N/A,-122.375120,47.541781,"{'address': '6760 34th Ave SW, Seattle, Washin..."
103,West Woodland,elementary school,5601 4th Ave NW,98107,N/A,-122.361901,47.670183,"{'address': '5601 4th Ave NW, Seattle, Washing..."
104,Licton Springs,option,1330 N. 90th St.,98103,option,-122.340502,47.694182,"{'address': '1330 N 90th St, Seattle, Washingt..."
105,BRIDGES,alternative and service,unknown street,unknown zip,alternative and service,0.000000,0.000000,{}
106,Cascade Parent Partnership,alternative and service,2919 1st Ave W.,98119,alternative and service,-122.358182,47.646280,"{'address': '2919 1st Ave W, Seattle, Washingt..."
107,Nova,alternative and service,2410 E Cherry St.,98122,alternative and service,-122.301141,47.608023,"{'address': '2410 E Cherry St, Seattle, Washin..."
108,Original Van Asselt,alternative and service,8311 Beacon Ave S,98118,alternative and service,-122.288083,47.529125,"{'address': '8311 Beacon Ave S, Seattle, Washi..."
109,South Lake,alternative and service,8601 Rainier Ave S,98118,alternative and service,-122.270014,47.525661,"{'address': '8601 Rainier Ave S, Seattle, Wash..."

In [16]:
#map all schools
import random
from arcgis.gis import GIS
#from arcgis.geocoding import geocoding
my_gis = GIS()
seattle = my_gis.map("Seattle, WA")

geocodes = school_df['geocode']
name = school_df['School']

i = 0
for school in geocodes:
    try:
        seattle.draw(school['location'], {"title" : name[i], "content" : school['address']},
                     {"type": "esriSMS","style": "esriSMSCircle","color": [0,255,0,255],"size": 6,
                      "angle": 0,"xoffset": 0,"yoffset": 0,
                      "outline": {"color": [0,0,0,255],"width": 0}})
    except:
        print("No address for:", (name[i]))
    i+=1
       
#seattle

No address for: Skills Center
No address for: BRIDGES

In [17]:
# get late bus data
late_bus_df = pd.read_pickle('../scraping_bus_data/bus_data.pk1')
late_bus_select_df  = late_bus_df[19:38]
late_bus_select_df

,Month,Day,Year,Bus Number,School,To/From,Time,Unit,Data Taken Month,Data Taken Day,Data Taken Year,Data Taken Hour,Data Taken Minute
19,December,21,2018,3,Adams,from,20,minutes,1,1,2019,21,6
20,December,21,2018,120,Loyal Heights,from,20,minutes,1,1,2019,21,6
21,December,21,2018,630,Queen Anne,from,20,minutes,1,1,2019,21,6
22,December,21,2018,148,Northgate,from,10,minutes,1,1,2019,21,6
23,December,21,2018,799,Gatzert,from,120,minutes,1,1,2019,21,6
24,December,21,2018,462,Washington,from,60,minutes,1,1,2019,21,6
25,December,21,2018,792,Kimball,from,120,minutes,1,1,2019,21,6
26,December,21,2018,402,Cleveland,from,60,minutes,1,1,2019,21,6
27,December,21,2018,624,Fairmount Park,from,120,minutes,1,1,2019,21,6
28,December,21,2018,464,Washington,from,60,minutes,1,1,2019,21,6
29,December,21,2018,795,Leschi,from,120,minutes,1,1,2019,21,6
30,December,21,2018,456,Meany,from,60,minutes,1,1,2019,21,6
31,December,21,2018,327,Washington,from,60,minutes,1,1,2019,21,6
32,December,21,2018,130,Maple,from,120,minutes,1,1,2019,21,6
33,December,21,2018,36,Dearborn Park,from,120,minutes,1,1,2019,21,6
34,December,21,2018,213,Viewlands,from,120,minutes,1,1,2019,21,6
35,December,21,2018,79,John Hay,from,60,minutes,1,1,2019,21,6
36,December,21,2018,317,Meany,from,60,minutes,1,1,2019,21,6
37,December,21,2018,576,TOPS,from,20,minutes,1,1,2019,21,6

In [18]:
# find the row of the school_df with the schools that have late buses
late_schools = school_df.loc[school_df.get('School').isin(late_bus_select_df.get('School'))]
late_schools

,School,Type,Street Address,Zip Code,option_alt,latitude,longitude,geocode
2,Cleveland,high school,5511 15th Ave S,98108,option,-122.313525,47.552310,"{'address': '5511 15th Ave S, Seattle, Washing..."
26,Meany,middle school,301 21st Ave E,98112,N/A,-122.304763,47.621574,"{'address': '301 21st Ave E, Seattle, Washingt..."
40,TOPS,k-8,2500 Franklin Ave EÃ¦,98102,option,-122.324580,47.642351,"{'address': '2500 Franklin Ave E, Seattle, Was..."
42,Adams,elementary school,6110 28th Ave NW,98107,N/A,-122.392953,47.673247,"{'address': '6110 28th Ave NW, Seattle, Washin..."
53,Dearborn Park,elementary school,2820 S Orcas St,98108,N/A,-122.295613,47.550880,"{'address': '2820 S Orcas St, Seattle, Washing..."
57,Fairmount Park,elementary school,3800 SW Findlay St,98126,N/A,-122.380323,47.552034,"{'address': '3800 SW Findlay St, Seattle, Wash..."
65,John Hay,elementary school,201 Garfield St,98109,N/A,-122.351791,47.633114,"{'address': '201 Garfield St, Seattle, Washing..."
67,Kimball,elementary school,3200 23rd Ave S,98144,N/A,-122.303323,47.574054,"{'address': '3200 23rd Ave S, Seattle, Washing..."
72,Leschi,elementary school,135 32nd Ave,98122,N/A,-122.291351,47.602152,"{'address': '135 32nd Ave, Seattle, Washington..."
74,Loyal Heights,elementary school,7735 25th Ave NW,98117,N/A,-122.388802,47.685623,"{'address': '7735 25th Ave NW, Seattle, Washin..."
78,Maple,elementary school,4925 Corson Ave S,98108,N/A,-122.318251,47.557655,"{'address': '4925 Corson Ave S, Seattle, Washi..."
85,Northgate,elementary school,11725 1st Ave NE,98125,N/A,-122.328841,47.714841,"{'address': '11725 1st Ave NE, Seattle, Washin..."
88,Queen Anne,elementary school,520 NE Ravenna Blvd,98155,option,-122.322877,47.677019,"{'address': '520 NE Ravenna Blvd, Seattle, Was..."
100,Viewlands,elementary school,10525 3rd Ave NW,98177,N/A,-122.360841,47.705967,"{'address': '10525 3rd Ave NW, Seattle, Washin..."

In [19]:
# calculate the total bus late time for each school
total_rows = int(late_schools.size/8)

late_time = (total_rows)*[0]
i = 0

for index_schools, row_schools in late_schools.iterrows():
    for index_buses, row_buses in late_bus_select_df.iterrows():
        if row_schools['School'] == row_buses['School']:
            #print(row_schools['School'],row_buses['School'])
            late_time[i] += row_buses['Time']
    i+=1
    #print(late_time)
    
late_schools['Late Time'] = late_time
late_schools

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

,School,Type,Street Address,Zip Code,option_alt,latitude,longitude,geocode,Late Time
2,Cleveland,high school,5511 15th Ave S,98108,option,-122.313525,47.552310,"{'address': '5511 15th Ave S, Seattle, Washing...",60
26,Meany,middle school,301 21st Ave E,98112,N/A,-122.304763,47.621574,"{'address': '301 21st Ave E, Seattle, Washingt...",120
40,TOPS,k-8,2500 Franklin Ave EÃ¦,98102,option,-122.324580,47.642351,"{'address': '2500 Franklin Ave E, Seattle, Was...",20
42,Adams,elementary school,6110 28th Ave NW,98107,N/A,-122.392953,47.673247,"{'address': '6110 28th Ave NW, Seattle, Washin...",20
53,Dearborn Park,elementary school,2820 S Orcas St,98108,N/A,-122.295613,47.550880,"{'address': '2820 S Orcas St, Seattle, Washing...",120
57,Fairmount Park,elementary school,3800 SW Findlay St,98126,N/A,-122.380323,47.552034,"{'address': '3800 SW Findlay St, Seattle, Wash...",120
65,John Hay,elementary school,201 Garfield St,98109,N/A,-122.351791,47.633114,"{'address': '201 Garfield St, Seattle, Washing...",60
67,Kimball,elementary school,3200 23rd Ave S,98144,N/A,-122.303323,47.574054,"{'address': '3200 23rd Ave S, Seattle, Washing...",120
72,Leschi,elementary school,135 32nd Ave,98122,N/A,-122.291351,47.602152,"{'address': '135 32nd Ave, Seattle, Washington...",120
74,Loyal Heights,elementary school,7735 25th Ave NW,98117,N/A,-122.388802,47.685623,"{'address': '7735 25th Ave NW, Seattle, Washin...",20
78,Maple,elementary school,4925 Corson Ave S,98108,N/A,-122.318251,47.557655,"{'address': '4925 Corson Ave S, Seattle, Washi...",120
85,Northgate,elementary school,11725 1st Ave NE,98125,N/A,-122.328841,47.714841,"{'address': '11725 1st Ave NE, Seattle, Washin...",10
88,Queen Anne,elementary school,520 NE Ravenna Blvd,98155,option,-122.322877,47.677019,"{'address': '520 NE Ravenna Blvd, Seattle, Was...",20
100,Viewlands,elementary school,10525 3rd Ave NW,98177,N/A,-122.360841,47.705967,"{'address': '10525 3rd Ave NW, Seattle, Washin...",120

In [20]:
#from arcgis.geocoding import geocoding
my_gis = GIS()
seattle_bus_map = my_gis.map("Seattle, WA")

geocodes = late_schools['geocode']
name = list(late_schools['School'])
late_time = list(late_schools['Late Time'])

#print(late_time)
i = 0
for school in geocodes:
    max_d = 8
    d = (max_d*(late_time[i]+30))/120
    seattle_bus_map.draw(school['location'], {"title" : name[i], "content" : school['address']},
                     {"type": "esriSMS","style": "esriSMSCircle","color": [255,0,125,255],
                      "size": d,
                      "angle": 0,"xoffset": 0,"yoffset": 0,
                      "outline": {"color": [0,0,0,255],"width": 1}})

    i+=1
       
seattle_bus_map

MapView(layout=Layout(height='400px', width='100%'))